# Generated by Django 5.1.4 on 2025-01-27 18:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название машины')),
                ('brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='Брэнд')),
                ('model', models.CharField(blank=True, max_length=20, null=True, verbose_name='Модель')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег (в км)')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('transmission', models.CharField(choices=[('ППР', 'Полный привод'), ('ПП', 'Передний привод'), ('ЗП', 'Задний привод')], max_length=50, verbose_name='Привод')),
                ('location', models.CharField(max_length=255, verbose_name='Адрес')),
                ('car_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('truck', 'Truck'), ('coupe', 'Coupe')], max_length=50, verbose_name='Класс автомобиля')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена аренды')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='Изображение (750x500px)')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='RareCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название машины')),
                ('brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='Брэнд')),
                ('model', models.CharField(blank=True, max_length=20, null=True, verbose_name='Модель')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег (в км)')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('transmission', models.CharField(choices=[('ППР', 'Полный привод'), ('ПП', 'Передний привод'), ('ЗП', 'Задний привод')], max_length=50, verbose_name='Привод')),
                ('location', models.CharField(max_length=255, verbose_name='Адрес')),
                ('car_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('truck', 'Truck'), ('coupe', 'Coupe')], max_length=50, verbose_name='Класс автомобиля')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена аренды')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='Изображение (750x500px)')),
                ('additional_images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, null=True, upload_to='cars/additional/'), blank=True, size=5, verbose_name='Дополнительные изображения')),
            ],
            options={
                'verbose_name': 'редкую машину',
                'verbose_name_plural': 'Редкие машины',
            },
        ),
    ]
