# Generated by Django 5.1.5 on 2025-01-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Брэнд'),
        ),
    ]
