# Generated by Django 5.1.4 on 2025-01-29 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'машину', 'verbose_name_plural': 'Все машины'},
        ),
        migrations.RemoveField(
            model_name='rarecar',
            name='additional_image_1',
        ),
        migrations.RemoveField(
            model_name='rarecar',
            name='additional_image_2',
        ),
        migrations.RemoveField(
            model_name='rarecar',
            name='additional_image_3',
        ),
        migrations.RemoveField(
            model_name='rarecar',
            name='additional_image_4',
        ),
        migrations.RemoveField(
            model_name='rarecar',
            name='additional_image_5',
        ),
        migrations.AddField(
            model_name='rarecar',
            name='car_ref',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rare_car', to='cars.car'),
        ),
    ]
