# Generated by Django 5.1.4 on 2025-01-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_car_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(
                upload_to="cars/", verbose_name="Изображение (750x500px)"
            ),
        ),
    ]
