# Generated by Django 5.1.4 on 2025-01-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_options_remove_rarecar_additional_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rarecar',
            name='additional_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='cars/additional_images/', verbose_name='Дополнительное изображение 1'),
        ),
        migrations.AddField(
            model_name='rarecar',
            name='additional_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='cars/additional_images/', verbose_name='Дополнительное изображение 2'),
        ),
        migrations.AddField(
            model_name='rarecar',
            name='additional_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='cars/additional_images/', verbose_name='Дополнительное изображение 3'),
        ),
        migrations.AddField(
            model_name='rarecar',
            name='additional_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='cars/additional_images/', verbose_name='Дополнительное изображение 4'),
        ),
        migrations.AddField(
            model_name='rarecar',
            name='additional_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='cars/additional_images/', verbose_name='Дополнительное изображение 5'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='rarecar',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель'),
        ),
    ]
