# Generated by Django 5.1.4 on 2025-01-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_alter_car_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="model",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Модель"
            ),
        ),
    ]
